rabbitmq:
  host: rabbitmq
  port: 5672

postgres:
  host: postgres
  port: 5432
  db: appdb

linkedin:
  REDIRECT_URI: "https://www.linkedin.com/developers/apps/verification/177c005c-a448-4a09-9312-e85cec6a4846"
  AUTH_URL: "https://www.linkedin.com/oauth/v2/authorization"
  TOKEN_URL: "https://www.linkedin.com/oauth/v2/accessToken"
  SCOPE: "r_liteprofile r_emailaddress w_member_social"